books/urls.py
from django.urls import path
from . import views
from . views import (SessoesCreateView, BooksCreateView, PostsCreateView)

app_name = 'book'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='Books-About'),
    path('denied/', views.denied, name='denied'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalhe'),
    path('novasessao/', SessoesCreateView.as_view(), name='criar-sessao'),
    path('novolivro/', BooksCreateView.as_view(), name='criar-livro'),
    path('novopost/<int:pk>/', PostsCreateView.as_view(), name='novopost'),
    path('detalhe-livro/<int:pk>/', views.DetalhesLivro.as_view(), name='detalhe-livro'),
]

django_books/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Sessoes(models.Model):
    title = models.CharField(max_length=100)
    sessao_date = models.DateField()
    
    def __str__(self):
        return self.title

class Books(models.Model):
    sessaoid = models.ForeignKey(Sessoes, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=100)
    author = models.CharField(max_length=50, default='Autor')
    description = models.CharField(max_length=250)
    sinopse = models.TextField()
    image = models.ImageField(upload_to='books/')
#   presented_by = models.CharField(max_length=50, default='Autor')
    presented_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.book_name

    def get_absolute_url(self):
        return reverse('book:detalhe-livro', kwargs={'pk': self.pk})

class Posts(models.Model):
    bookid = models.ForeignKey(Books, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content =models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

 #   def get_absolute_url(self):
 #       return reverse('book:detalhe-livro')
 #      return reverse('book:index')

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics/')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
      model = Profile
      fields = ['image']  

books/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import F
from django.shortcuts import redirect
from .mixins import ValidateUsersPermissions
from .models import Sessoes, Books, Posts
from django.contrib import messages

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'books/index.html'
    model = Sessoes
    context_object_name = 'displaybook'

    def get_queryset(self):
        return Sessoes.objects.order_by('sessao_date')[:20]

class DetailView(generic.DetailView):
    model = Sessoes
    template_name = 'books/detalhe.html'

class DetalhesLivro(DetailView):
    model = Books
    template_name = 'books/detalhe_livro.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['sessao'] = Books.objects.select_related('sessaoid').get(pk=self.kwargs['pk'])
        return context

class SessoesCreateView(ValidateUsersPermissions, CreateView):
    model = Sessoes
    fields = ['title', 'sessao_date']
    
    def get_success_url(self):
        return reverse('book:index')

class BooksCreateView(ValidateUsersPermissions, CreateView):
    model = Books
    fields = ['sessaoid', 'book_name', 'author', 'description', 'sinopse', 'image']

    def form_valid(self, form):
        form.instance.presented_by = self.request.user
        form.save()
        return super().form_valid(form)

class PostsCreateView(CreateView):
    model = Posts
    fields = ['title', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['book'] = Books.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.posted_by = self.request.user
        form.instance.bookid_id = self.kwargs['pk']
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('book:detalhe-livro', kwargs={'pk': self.kwargs['pk']})

def about(request):
    return render(request, 'books/about.html', {'title': 'About'})

def denied(request):
    return render(request, 'books/denied.html', {'title': 'Acesso Restrito'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
#            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='Normal_Users')
            user.groups.add(group)
            messages.success(request, f'A tua conta foi criada. Já podes realizar o Login')
            return redirect('login')
    else:
        form = UserRegisterForm()   
    return render(request, 'users/register.html', {'form' : form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, 
                                   request.FILES, 
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'O teu perfil foi atualizado!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

books/templates/books/about.html
{% extends "books/base.html" %}
{% load static %}

{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            <img widht="225" height="225" src="{% static '/heart.jpg' %}" alt="My image">
        </div>
        <div class="col-md-12">
            <p>O nosso clube de leitura surge da tremenda paixão pelos livros e da vontade inabalável dos nossos colegas 
            António Jorge, da Ror de Livros e Ana Pereira, da Xylocopa Books, partilharem os seus projetos com a nossa comunidade. 
            Um encontro feliz que veio proporcionar aos afortunados membros deste club de leitura a troca de opiniões, reflexões e 
            críticas sobre os livros que vamos lendo e trazendo para estas sessões. Sendo ainda, a prática da leitura, uma atividade 
            pouco frequente entre os portugueses, e considerando o enorme valor cultural gerado por este pequeno grupo de leitores, 
            achámos que para além das sessões físicas, que realizamos no último Domingo de cada mês, e que por várias razões têm uma 
            lotação limitada, seria uma boa ideia abrir as portas virtuais desta experiência às pessoas que estão interessadas em 
            acompanhar e contribuir para esta causa mui nobre que é o ato de ler.
            <br><br>    
            </p>
        </div>
    </div>
    <div class="row">
        <p>
        No nosso site podem encontrar toda a informação sobre as diversas sessões e os livros que foram apresentados. 
        Poderão também criar uma conta e contribuir, de forma construtiva, com comentários sobre as várias obras apresentadas.    
        </p>    
    </div>
</div>
{% endblock content %}

books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href=" {% static '/books/main.css' %}">

    {% if title %}
        <title>Que farei com este livro? - {{ title }}</title/>
    {% else %}
        <title>Que farei com este livro?</title>   
    {% endif %}

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'book:index' %}">Que farei com este livro?</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'book:index' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'book:Books-About' %}">Sobre Nós</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
              {% if user.is_superuser %}
                <a class="nav-item nav-link" href="{% url 'book:criar-sessao' %}">Nova Sessão</a>  
                <a class="nav-item nav-link" href="{% url 'book:criar-livro' %}">Novo Livro</a>
              {% endif %}
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Perfil</a>  
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Sair</a>
              {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Entrar</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Registar-se</a>
              {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-12">
              {% if messages %}
                  {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                          {{ message }}
                      </div>
                  {% endfor %}
              {% endif %}
              {% block content %} {% endblock content%}
          </div>
        </div>
      </main>
      <br><br>
  <footer class="text-lg-start">
          <!-- Grid container -->
          <div class="container p-4">
            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">Site</h5>

                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white" href="{% url 'book:index' %}">Home</a>
                  </li>
                  <li>
                    <a class="text-white" href="{% url 'book:Books-About' %}">Sobre Nós</a>
                  </li>
                  <li>
                    <a class="text-white" href="#">Contactos</a>
                  </li>
                  <li>
                    <a class="text-white" href="#">Politíca de Privacidade</a>
                  </li>
                  <li>
                    <a class="text-white" href="#">Termos de Utilização</a>
                  </li>
                </ul>
              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase mb-0">INFORMAçÃO ÚTIL</h5>

                <ul class="list-unstyled">
                  <li>
                    <a class="text-white" href="#">FAQ</a>
                  </li>
                  <li>
                    <a class="text-white" href="https://www.portaldaliteratura.com/" target="_blank">Portal da Literatura</a>
                  </li>
                  <li>
                    <a class="text-white" href="https://www.ffms.pt/pt-pt/livraria" target="_blank">Fundação FMS</a>
                  </li>
                  <li>
                    <a class="text-white" href="https://www.cupertino.pt/fundacao-cupertino-de-miranda/" target="_blank">Fundação Cupertino M</a>
                  </li>
                </ul>
              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">PARCEIROS</h5>

                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white" href="https://www.xylocopabooks.pt/" target="_blank">Xylocopa Books</a>
                  </li>
                  <li>
                    <a class="text-white" href="https://www.facebook.com/rordelivros/" target="_blank">ROR de Livros</a>
                  </li>
                </ul>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </div>
          <!-- Grid container -->

          <!-- Copyright -->
          <div class="text-center p-3" style="background-color:#0f0e0e">
            © 2023 Copyright: MF
          </div>
          <!-- Copyright -->
</footer>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

books/templates/books/books_form.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col">
        </div>
        <div class="col-4" align="left">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Criar Livro em Sessão</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Criar</button>
                </div>
            </form>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

books/templates/books/denied.html
{% extends "books/base.html" %}
{% block content %}
<iframe src="https://giphy.com/embed/8AjfZQI2SDZ2qrDdtO" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/redandhowling-animation-cat-8AjfZQI2SDZ2qrDdtO">via GIPHY</a></p>
{% endblock content %}

books/templates/books/detalhe.html
{% extends "books/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <h4> {{ sessoes.title }} - {{ sessoes.sessao_date }} </h4>
    </div>
    <br>
    <a class="btn btn-outline-primary btn-sm" href="{% url 'book:index' %}">Voltar às Sessões</a>
    <br>
    <br>
    <div class="row justify-content-center">
        {% for livros in sessoes.books_set.all %}
            <div class="col-md-3 book margens"> 
                <img widht="128" height="200" src= {{ livros.image.url }}/>
                <p><a href="{% url 'book:detalhe-livro' livros.id %}"> {{ livros.book_name }} </a></p>
                <p> Autor: {{ livros.author }}</p>
                <p style="font-size:11px">Apresentado por: {{ livros.presented_by}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

books/templates/books/detalhe_livro.html
{% extends "books/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <h4>{{ sessao.sessaoid.title }} - {{ sessao.sessaoid.sessao_date }}</h4>
    </div>
    <br>
        <a class="btn btn-outline-primary btn-sm" href="{% url 'book:detalhe' sessao.sessaoid.id %}">Voltar à Sessão</a>
        {% if user.is_authenticated %}
            <a class="btn btn-outline-primary btn-sm" href="{% url 'book:novopost' object.id %}">Post</a>
        {% endif %}
    <br>
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-2">
                <img class="icenter" align="center" widht="128" height="200" src= {{ object.image.url }}/>   
            </div>
            <div class="col-8">
                <h5> {{ object.book_name }} </h5> 
                <h6> {{ object.author }}</h6>
                <h6> {{ object.description }} </h6>
                <p style="font-size:11px">Apresentado por: {{ object.presented_by }}</p>
                <p style="font: size 13px"> {{ object.sinopse }} </p> 
            </div> 
        </div>
    </div>
        {% if books.posts_set.all %}
            <h3>Posts</h3>
        {% endif %}
        {% for posts in books.posts_set.all %}
        <div class="container"> 
            <div class="row">
                <div class="col">
                </div>
                <div class="col-8" align="left">
                    <article class="media content-section">
                                <div class="media-body">
                                    <div class="article-metadata">
                                        <img class="rounded-circle article-img" src="{{ posts.posted_by.profile.image.url }}">
                                        {{ posts.posted_by }}
                                        <small class="text-muted"> {{ posts.date_posted|date:"F d, Y" }}</small>    
                                    </div>
                                    <h4 class=""article-title">{{ posts.title }}</h4>
                                    <p class="article-content">{{ posts.content }}</p>
                                </div>
                    </article>
                </div>
                <div class="col">
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock content %}

books/templates/books/index.html
{% extends "books/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h4>Bem-vindo</h4>       
            <p>Somos uma comunidade civil que partilha o gosto pela leitura.
                Aqui apresentamos o resultado das nossas sessões
                mensais. É, desde já, convidado a participar e a comentar os livros apresentados, 
                basta criar uma conta e está pronto a partilhar. O debate é importante. Acreditmaos
                que a troca de ideias enriquece a nossa experiência e percepção dos textos literários.
        </div>
        <div>
            &nbsp;
        </div> 
         <div class="col-md-12 brush">
            <p class="bgfrase text-center">Os livros são refúgos da memória, espelhos onde nos olhamos para podermos
                ser mais parecidos com aquilo que desejamos ser. Estes frágeis universos são 
                a nossa força. É imprescindível cuidar de quem lê.
            </p>    
        </div>
        <div class="col-md-12">       
            <p style="font-size:10px">Manifesto pela leitura, Irene Vallejo.</p>
        </div>
        <div>
            &nbsp;
        </div> 
    </div>
    <div class="row fcolor">
        <h4>Sessões</h4>
    </div>
    <div class="row bgsessoes">
        {% if displaybook %}
            {% for c in displaybook %}
            <div class="col-md-2 book margens">
                    <h6><a href="{% url 'book:detalhe' c.id %}"> {{ c.title }}</a></h6>
                    <p style="font-size:11px">{{ c.sessao_date }}</p>
            </div>       
            {% endfor %}
        {% else %}
            <p>Não há sessões</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

books/templates/books/posts_form.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-2">   
                <img class="icenter" align="center" widht="128" height="200" src= {{ book.image.url }}/>   
            </div>
            <div class="col-md-6">
                <h4 style="color: grey">Este é o livro que está a comentar:</h4>
                <h5> {{ book.book_name }} </h5>
                <p style="font-size:11px">Autor: {{ book.author }}</p>
                <p style="font-size:11px">Descrição: {{ book.description }}</p>
                <p style="font-size:11px">Apresentado por: {{ book.presented_by }}</p>
            </div>
        </div>
    </div>
    <br>
    <div class="container"> 
        <div class="row">
            <div class="col">
            </div>
            <div class="col-8" align="left">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Criar Post</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Criar</button>
                    </div>
                </form>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock content%}

books/templates/books/sessoes_form.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col">
        </div>
        <div class="col-4" align="left">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Criar Sessão</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Criar</button>
                </div>
            </form>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col">
        </div>
        <div class="col-8" align="left">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Entrar</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Entrar</button>
                    <small class="text-muted ml-2">
                        <a href="{% url 'password_reset' %}">Recuperar Password</a>
                    </small>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Precisa de um conta? <a class="ml-2" href="{% url 'register' %}">Registe-se aqui</a>
                </small>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "books/base.html" %}
{% block content %}
    <h2>Fez Logout com sucesso!</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Entrar Novamente</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-4" align="left">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Nova Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Pedir Nova Password</button>
                </div>
            </form>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "books/base.html" %}
{% block content %}
    <div class="alert alert-info">
        A sua password foi alterada com sucesso.
    </div>
<a href="{% url 'login' %}">Faça Login aqui</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-4" align="left">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Nova Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Nova Password</button>
                </div>
            </form>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "books/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Foi enviado um e-mail com instruções para criar a sua nova password
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col">
        </div>
        <div class="col-6" align="left">
            <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Informação do Perfil</legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Actualizar</button>
                </div>
            </form>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col">
        </div>
        <div class="col-6" align="left">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Regista-te Agora</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Regista-te</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Já tem conta? <a class="ml-2" href="{% url 'login' %}">Entrar</a>
                </small>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}